import { readdirSync } from "node:fs";
import { join } from "node:path";
// from "vitest/config", not "vite": vite's own defineConfig has no `test` key
// in its type, so the vitest options below would fail `pnpm typecheck`. It
// re-exports vite's config unchanged with that key added.
import { defineConfig } from "vitest/config";

// Every .html file in the repo is a page and a build entry, so a multi-page
// hand-written site needs no build config: add pages, link them, ship.
// (Vite's default would build only the root index.html and silently drop the
// rest from dist/ — fine locally, 404s deployed.)
// `assets-src` and `public` hold tens of megabytes of models and audio and not one
// .html between them; walking them on every config load is pure cost.
const SKIP = new Set([
  "node_modules", "dist", "spec", "scripts", "reflections", "assets-src",
  "public", "instructions", "build",
]);

// Local diagnostics that are not part of the site. They are real pages and
// they work, but a deployed audio probe is a page a pod can land on that is
// not the game -- and every shipped page has to carry a description, a card
// and a landmark, which a scratch harness has no reason to. Keeping them out
// of the build is cheaper than dressing them up as pages they are not.
const DEV_ONLY = new Set(["audio-probe.html"]);

function htmlEntries(dir = "."): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    if (entry.name.startsWith(".") || SKIP.has(entry.name)) return [];
    const path = join(dir, entry.name);
    if (entry.isDirectory()) return htmlEntries(path);
    if (DEV_ONLY.has(entry.name)) return [];
    return entry.name.endsWith(".html") ? [path] : [];
  });
}

// `base: "./"` makes built asset URLs relative, so the site works under any
// GitHub Pages path (username.github.io/your-repo/) without further config.
export default defineConfig({
  base: "./",
  build: {
    rollupOptions: {
      input: htmlEntries(),
    },
  },
  server: {
    watch: {
      // DO NOT WATCH assets-src/. It holds the untracked SOURCE models --
      // 84 MB and growing -- and nothing in it reaches the build directly:
      // `pnpm assets` derives public/assets/ from it, and only public/ is
      // copied. (It was `assets/` until that name was found to collide with
      // the URL public/assets/ serves; see scripts/compress-assets.ts.)
      //
      // Watching it is not merely wasteful, it is fragile. Dropping a new
      // model in there killed the dev server outright:
      //
      //   Error: EBUSY: resource busy or locked, watch
      //   'assets-src/sam/scene.bin'
      //
      // A 20 MB file still being written cannot be watched on Windows, and
      // chokidar raises that as an unhandled error rather than skipping the
      // file. So the failure mode of ADDING AN ASSET was the whole dev server
      // exiting with a stack trace about a file the build never reads.
      // Widened after this recurred on `instructions/` -- a spec document being
      // written killed the server the same way a model did. Ignoring one
      // directory at a time treats instances; the CLASS is "anything the
      // browser never fetches". Nothing below reaches a page: assets-src/
      // holds untracked sources that `pnpm assets` derives public/ from, and
      // the rest is prose.
      //
      // public/ is the exception to that phrasing and still belongs here, which
      // is worth stating rather than leaving as an inconsistency. The browser
      // DOES fetch it — 36 MB of glTF, textures and audio — but nothing in it
      // is edited: it is generated by `pnpm assets`, and a changed model needs a
      // reload regardless because HMR cannot hot-swap a mesh. So watching it
      // buys nothing and costs the same crash the comment above describes.
      //
      // It bit again, from an angle the earlier fixes did not cover: saving a
      // new card.png into public/ from a browser leaves a partial
      // `Unconfirmed 256061.crdownload` there for a second, and the dev server
      // exited with EBUSY on a file that is not even part of the site. Twice
      // now the failure mode of ADDING AN ASSET has been the whole server
      // dying, so this ignores the directory rather than waiting for a third
      // way in.
      ignored: [
        "**/assets-src/**",
        "**/public/**",
        "**/dist/**",
        "**/instructions/**",
        "**/reflections/**",
        "**/*.md",
        "**/.git/**",
      ],
    },
  },

  test: {
    // Vitest's default glob would collect `src/flight.test.js` directly and
    // fail it as "no test suite found": that file is the GAME's suite —
    // plain assertions with its own pass/fail count, framework-free by
    // design (CLAUDE.md §18) — and it has no describe/it blocks to find.
    //
    // It still runs under `pnpm check`, but through `spec/vector.test.ts`,
    // which imports it and asserts the count is green. One suite, two
    // harnesses; this glob just says which files are vitest's to drive.
    include: ["spec/**/*.test.ts", "scripts/**/*.test.ts"],

    // jsdom, because the game's suite is imported here and it reads document,
    // window.innerWidth and location -- the pointer-steering checks need a
    // viewport to measure deflection from. spec/headless-canvas.ts adds the
    // one thing jsdom lacks, a 2D context; its header says why that is a
    // legitimate double and not a hole in the gate.
    environment: "jsdom",
    setupFiles: ["spec/headless-canvas.ts"],
  },
});
